
language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

addons:
    postgresql: "9.4"

env:
    - FISCAL_PACKAGE_ENGINE=postgresql://postgres@/os
before_install:
    - virtualenv ./pyenv --distribute
    - source ./pyenv/bin/activate
install:
    - pip install -e .
    - pip install psycopg2 nose flask-testing coverage future futures
    - pip install python-dateutil coveralls unicodecsv
    - pip install -U git+git://github.com/okfn/datapackage-py.git
before_script:
    - psql -c 'create database os;' -U postgres
    - python -m nose --version
script:
    - python -m nose --with-coverage --cover-package=babbage_fiscal -w tests
after_success:
    - coveralls
