dist: trusty

language:
  python

python:
  - 3.6

services:
  - docker

sudo: required

addons:
    postgresql: "9.4"

env:
    global:
        - OS_API_ENGINE=postgresql://postgres@/postgres
        - DPP_DB_ENGINE=postgresql://postgres@/postgres
        - OS_ELASTICSEARCH_ADDRESS=localhost:9200
        - ELASTICSEARCH_ADDRESS=localhost:9200
        # DOCKER_USERNAME
        - secure: stuHESFXIArG1T1u4ddSwOsrNMjQ9TSAw/UYdWqs5rdkkBz+tYA2S0f8fqpE7kLffwcsnie0lWAuF5HpGWsb42ZAgDnY8ENJBds+65378uT7CepsM+A4GkLdSYGQTgrhTgAmbLJtBIt4vzELisW2V/G2rSlrfS1OjQZKaDeoqXQLOslCE/05oKFvyYw1YN4fpPFqjJVeBNBqXmVYSjBz7CrinUcxQfqUhMqGfgF7VgjTO4Jt+vKU4ym3nKgqyRufYWbgmbEoevi/3JAHuWx73kCv7MVnQQaBdyXdPLQLLqmR/PSxkUsAfH+rUWdam+mF3txB9si+Pw17LUaV+hnVJ+N8zpOTIkxN1bDHilWWdrw52lM5n/7//uBABAa2DZO2+8F2o7oh1sH5anKCRv48dvpboRsqoG+ymnGsDv01QlgcWcZ8hcj8KOC6kmbnjNK9hCk+WywWKo2LSs8+FfD/fTfBeUPKB1lPLFn64DzpOLGzbAUhvQ7bsP+Py1awf6ClcHgSXvWdJQTEuOGr8eJ7zPXE4BC2+tWXEDM+0rOiF2saGqXzQqS5BGmtvtk+U7ujquFSfYm038PLl7uYU+pdBRSI3p5rC1aAWYaPayyGUnnZwK3rMta/ih/GVM6LZtdkXn1wVHitjrDRVTdVF/jwZN7vzltjmormMMPAKWIHK9Q=
        # DOCKER_PASSWORD
        - secure: eJo9+lYTblyEztl5zZ7+x3JJBNvC96dxHFYiR4JZR3mGjvXnw6q//t821LB6bA9jmnlE15PjU1iOrn/eZuiu+uizEc60VdSZOq9y1CAFVR27ck8VXLAFNpLCpe39Ybu3zhYV5SpH2GoHaNhBvoxxWHXD7xhZ6AgtX6xHPzmwyfB7kzpXvuhZK/gAO3nYiWDacNyfDIcRKMceHLgK698p+eau6iUnL28D4gQPadyHXN8jFVG61oT//S1OedBZUROrJOTOXeJqC4Zp3uDwGnfGsLPQZkwDxfJQBgqxCsohf2hj09itJQoPSzpm3/rMrswciYqkJqIGElO8QT42qjlRSv6Qzwu/jlbCgaS5tgS236lXxT2qGwI762f+WfSDqOkXRBI+lKMb66XJlrjAdtAdcSIlb7w16teIqqhyHHrY9aMnsvAnY7mK7QlPYtO0HueRC6C58cc6feoz6pyleWYky0lxfmsHtZp+dmOyAIWo7W+ctUvOr108cCLsoP4MNmH/RMpx8EFpthgpiTNqvd3RCzQitK/nPdoiJcDmfLshCNs9Zi2iZ909TbsaSriKBBB4l/m0Z8BqVKLlN7jjESHkttKpxIp6MYh3Kw9WIOUAvxVSvaPe/z6fzrIYMXqHinxpc9yQn4FcegLUFtsUvPIlEHgknpBwJFZEdAc31YKzMR8=

before_install:
  - sudo rm -f /etc/boto.cfg
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.11.deb && sudo dpkg -i --force-confnew elasticsearch-5.6.11.deb && sudo service elasticsearch restart
  - nvm install 8
  - nvm use 8
  - npm install -g os-types
  - sudo apt-get install libleveldb-dev libleveldb1 libpq-dev python3-dev

install:
  # Will build local Dockerfile as part of ci-run (docker-compose up)
  - make ci-run
  - pip install tox coveralls 'datapackage-pipelines[speedup]>=1.7.1' datapackage-pipelines-fiscal==1.1.0 psycopg2-binary

before_script:
  - sleep 30
  - curl localhost:9200
  - cd tests/sample_data && ls && dpp && dpp run --verbose --concurrency=8 all
  - cd ../../

script:
  - make ci-test
  - tox

after_success:
  - coveralls
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make ci-push-tag TAG="${TRAVIS_PULL_REQUEST_BRANCH////_}"; fi'

deploy:
  # deploy master to latest tag
  - provider: script
    script: make ci-push
    on:
      branch: master
