
language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

addons:
    postgresql: "9.4"

env:
    - OS_API_ENGINE=postgresql://postgres@/os
install:
    - python -m pip install --upgrade pip
    - python -m pip install pytest flask-testing coverage coveralls
    - python -m pip install git+git://github.com/okfn/tabulator-py.git
    - python -m pip install git+git://github.com/okfn/datapackage-py.git
    - python -m pip install git+git://github.com/openspending/babbage.fiscal-data-package.git
    - python -m pip install -e .
    - python -m pip install -U git+git://github.com/openspending/babbage.git
before_script:
    - psql -c 'create database os;' -U postgres
    - python -m pytest --version
script:
    - python -m coverage run --source os_api -m pytest
after_success:
    - coveralls
