language: python
python:
- 3.6
services:
- docker
addons:
  postgresql: '9.4'
env:
  global:
  - OS_API_ENGINE=postgresql://postgres@/postgres
  - DPP_DB_ENGINE=postgresql://postgres@/postgres
  - OS_ELASTICSEARCH_ADDRESS=localhost:9200
  - ELASTICSEARCH_ADDRESS=localhost:9200
  - secure: c9VAIqVjR7ZR9dzicsOFtTB+FjCxMmSm+IRPjHmj6Mci5ED+6VAYbo1xxwqqypjfxI3o+nwifdG/Y06R3E5YmagFH3BRFOrff7/l4YfnnJz8zOE8jV5Ma56BgMSC/QMEMTBcYP+wapu60JpgKwJNQnCJbsHRR3oa6/ReS4qw0yg9nSU2XaoMk6OMSsFJtSBUPehnrRQohwv3sTUAGH1UEeH6/yPT847n1dYBLtD9y38eXFj+WPZ33+5y7fYorTHcS6yHPEElTMjMqcZGmxppIcR78JBsgQRs3+yyY6AgIQJy2khgEtltl4M0wfZzTZu3TNxaT/N++foYKcqBNVAxkILHpI0L3G0S176itQjY5IuyqR4BpJ/BCPMacLrmXjqMIETSAxaBXbFXL/8s6ceE1SE7mFPjtjY0/vPEFgJbX1dvwSNTfq2jM3T0pcWPFYeAQRkTKyxUdX9O+9KhmMO+5TTJncB0CHxX9V9yado3gmhFhlIBsqjmdQq+nSXJKh+VgPfh7W2qiuPAvAb/pUsqGMatN0mVGRybHMuRTtsJpuo0wJoAcdmcB0/ClCtoPrcM0sTqZKye59Qwvq8U5RbR2vaWcXBXjR6r4SxkSOGvqCcNaq/Heq5+qk+Vt+v/aHlfs4RbVi+CYbKvpfPSn27e01hEvO7LsaKxCx3tXvHJ0/g=
  - secure: s31RgqzHifoPOzf7SMS3xlrHHyeX90fWVZPLJfGg7ivunAJ+AE8kbSNabZUPR0yphZZHfLQPZtHHv3DThraz29vx1tZk1y2hS7tr1NdA7MqMgwD26mmBgOqTMXdMJMiRUTKg7Y3cQq84GNH4Mif1q6nvtfo4Fu1lNHwrBHwNl5WBr12RK68BHoqwXbh+zzauSn/TLCdji2Q6ijfGkaoOOQOadsIYv/yxBbhL4GKSQC0P3gvMl5JR1vquaL23EAwUI93Sc284m7pgZCCku5UKVEPsFu3Aoq9t81WEazzsYOWFreHmRgDDzPcxW5o6vtRQ/8kSCgTWMWHMLYtcgftIlHhclsR+btqA3TIizkZVjlfHtVAyJ9gc02ac3b/F9Ry/YHBWqkdXla5nMZyPLwMUtRWIRCWWiwbY6jelcu6AwFqOi1ORn85zZv27XJqQAnDm2X9QhdTz2KIdzDW653TUUH8kkMm+xHdWqsCxwnyFrTuwXuLokVspR3JXJYuDU+MsfzuQOvOpx25nm34EdELzkakSRoit1iqYSg5ljs+T1qNP1owZS99VwksC3KEyHxus3xpDT5M5JhcAUHp1TUafcdW7ED7M2kfUtf0Hs9S11Y4MzySYHcfiGJpPBa8tIxZVmnPh+HAdZywij2b64uijWkRGw/Kw8J+MiKqqNrlrkqo=
before_install:
- sudo rm -f /etc/boto.cfg
- docker run -d -p 9200:9200 bitnami/elasticsearch:5.6.4
- nvm install 8
- nvm use 8
- npm install -g os-types
- sudo apt-get install libleveldb-dev libleveldb1v5 libpq-dev python3-dev
install:
- pip install tox coveralls 'datapackage-pipelines[speedup]>=2.0.0,<3' 'datapackage-pipelines-fiscal>=1.2.0'
  psycopg2-binary
before_script:
- curl localhost:9200
- cd tests/sample_data && ls -la && dpp
- dpp run --verbose --concurrency=8 all
- cd ../../
script:
- tox
after_success:
- coveralls
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make ci-push-tag TAG="${TRAVIS_PULL_REQUEST_BRANCH////_}";
  fi
deploy:
- provider: script
  script: make ci-push
  on:
    branch: master
