version: "3"

services:

  os-api:
    build: .
    container_name: os-api
    environment:
      OS_API_ENGINE: postgresql://postgres@db/postgres
      OS_ELASTICSEARCH_ADDRESS: es:9200
      OS_API_CACHE: redis
      OS_API_CACHE_TIMEOUT: 86400
      OS_CHECK_ES_HEALTHY: 'True'
    restart: always
    depends_on:
      - db
      - es
      - redis

  redis:
    image: 'redis:3.2-alpine'
    expose:
      - 6379
    # ports:
    #   - "6379:6379"

  db:
    image: 'postgres:10-alpine'
    expose:
      - 5432
    # ports:
    #   - "5432:5432"

  es:
    image: bitnami/elasticsearch:5.6.4
    expose:
      - 9200
      - 9300
    # ports:
    #   - "9200:9200"
